const CategoryIcon = {
    "สินค้าเบ็ดเตล็ด (Miscellaneous)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLV_1_Health_69f9a5edd1.png&w=32&q=75",
    "เครื่องดื่ม (Drinks & Beverages)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLV_1_Beverage_cb569de5b4.png&w=32&q=75",
    "ผลิตภัณฑ์ซักผ้า และดูแลผ้า (Laundry Products)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLaundry_supplies_796f2569c7.png&w=32&q=75",
    "เครื่องปรุงรส-น้ำมัน (Seasoning-Oil)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLV_1_Grocery_de89330f07.png&w=32&q=75",
    "เครื่องสำอางค์และผลิตภัณฑ์ดูแล (Cosmetics and Care Products)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FSkin_care_and_Make_up_40442528c1.png&w=32&q=75",
    "ขนม (Appetizer)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FSnacks_and_Confectionery_b5b5ccfacf.png&w=32&q=75",
    "อาหารกระป๋อง-อาหารแห้ง (Canned Food,Dry Food)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FCanned_and_Packaged_food_e2a1551720.png&w=32&q=75",
    "ผลิตภัณฑ์ดูแลเส้นผม (Hair Care Products)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FSmart_Shopper_L2_Health_and_Beauty_9f3e1c5684.png&w=32&q=75",
    "ผ้าอนามัย ผ้าอ้อม กระดาษทิชชู่ (Sanitary Pad,Diapers)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FHousehold_paper_products_a5ff70fc04.png&w=32&q=75",
    "นม": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FMilk_c1ffe6638c.png&w=32&q=75",
    "ผลิตภัณฑ์ทำความสะอาดและดูแลผิวกาย (Cleaning Products And Take Care Of The Body)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FPersonal_care_06e5f8c819.png&w=32&q=75",
    "ของใช้ในบ้าน": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLV_1_House_caf75bd1c1.png&w=32&q=75",
    "ผลิตภัณฑ์สำหรับผู้หญิง": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FPersonal_care_06e5f8c819.png&w=32&q=75",
    "เครื่องเขียนและอุปกรณ์สำนักงาน": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FWriting_and_drawing_instrument_accessories_39cd462bab.png&w=32&q=75",
    "กาแฟ เครื่องชง ครีมเทียม": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FInstant_coffee_4980980278.png&w=32&q=75",
    "ผลิตภัณฑ์ดูแลช่องปาก": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FOral_care_0a5544af94.png&w=32&q=75",
    "ผลิตภัณฑ์สำหรับเด็ก": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLV_1_Baby_59dc4c5ffb.png&w=32&q=75",
    "ผลิตภัณฑ์สำหรับผู้ชาย": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FPerfume_and_Cologne_f1e4bdefbe.png&w=32&q=75",
    "เครื่องดื่มแอลกอล์ฮอล์": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FL2_Imported_drinks_V1_f2c642eafb.png&w=32&q=75",
    "ผลิตภัณฑ์ทำความสะอาด (Cleaning Products)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FCleaning_and_personal_cares_44a144a97e.png&w=32&q=75",
    "อาหารเสริม (Supplementary)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FSkin_care_and_Make_up_40442528c1.png&w=32&q=75",
    "อาหารแช่แข็ง": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FFrozen_38f45044c3.png&w=32&q=75",
    "อุปกรณ์อ๊อฟฟิต (OFFICE)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLV_1_Office_8aac6df695.png&w=32&q=75",
    "เครื่องใช้ไฟฟ้า (electrical appliance)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLV_1_Electric_9be3775dcf.png&w=32&q=75",
    "ยาสามัญประจำบ้าน (Household Remedy)": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FHealth_care_442ec1a7ab.png&w=32&q=75",
    "สังฆภัณฑ์และสังฆทาน": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FMonk_and_Merits_4dca7478ce.png&w=32&q=75",
    "อาหารสัตว์": "https://www.makro.pro/_next/image?url=https%3A%2F%2Fstrapi-cdn.mango-prod.siammakro.cloud%2Fuploads%2FLV_1_Pet_d85c9ed01a.png&w=32&q=75",
}

export default CategoryIcon;